# ehelp-utils.R
#  -- M.Ponce


#############################################################################################
##	Utilities file for the eHelp apckage
#
#	Mostly IO routines
#################################################################################################


# Define methods associated with ehelp.obj
print <- function(ehelp.obj){
#' method associated with ehelp objects
#' @param  ehelp.obj  ehelp object
#' @keywords internal
       UseMethod("print",ehelp.obj)
}

print.ehelp <- function(ehelp.obj,coloring=T) {
#' function associated to the ehelp object method
#' @param  ehelp.obj  ehelp object
#' @param  coloring  whether to use colors or not when displaying the help
#' keywords internal

   # header
   lines <- paste0("---------------------------------------------------------------",'\n', sep='')

   clrPalette <- ehelp.palette()
   #print(ehelp.obj)
   cat(lines)
   #print(ehelp.obj$txt)
   for (obj.line in seq_along(ehelp.obj$code)) {
	if (coloring) {
		clr <- list("","")
		#print(ehelp.obj$code[obj.line])
		if (ehelp.obj$code[obj.line] %in% clrPalette$codes) 
			# select here the color-palette: $color or $bw
			clr <- clrPalette$color[ clrPalette$code == ehelp.obj$code[obj.line] ][[1]]
		#print(paste0(clr,ehelp.obj$txt[obj.line]))
		cat( paste0(clr[[1]], ehelp.obj$txt[obj.line], clr[[2]]) )
	} else {
		cat(ehelp.obj$txt[obj.line])
	}
   }
   # footer
   cat('\n',lines)
}


#################################################################################################

### OUTPUT functions to save information to files...

processOutput <- function(ehelp.obj, fnName,fnCorpus, output) {
#' function to process the type output requested
#' @param  ehelp.obj  ehelp object generated by the ehelp() fn
#' @param  fnName   name of the function
#' @param  fnCorpus  function definition
#' @param  output  type of output, valid options are "txt", "TXT" or "none"
#' @keywords internal

        # valid options are "txt", "TXT", "html", "HTML", "latex", "LATEX" or "none"
	valid.outputFmts <- c("none", "txt","TXT", "ascii","ASCII", "html","HTML", "latex","LATEX", "markdown","MARKDOWN")
	# txt: output the help of the fn in plain "txt" 
	if (output=="txt") {
		#write.ehelp(ehelp.obj['txt'], file=paste0(fnName,"-eHelp.txt"))
		write.fmt(ehelp.obj,output,paste0(fnName,"-eHelp.txt"))
	# TXT: output the help of the fn in plain "txt" + listing of the fn
	} else if (output == "TXT") {
                #write.ehelp(ehelp.obj['txt'], file=paste0(fnName,"-eHelp.TXT"))
		write.fmt(ehelp.obj,output,file=paste0(fnName,"-eHelp.TXT"),leaveOpen=T)
                write.Fncorpus(fnName, fnCorpus, file=paste0(fnName,"-eHelp.TXT"))
	# html: output the help of the fn in HTML format
        } else if (output == "html") {
		#write.html(ehelp.obj, file=paste0(fnName,"-eHelp.html"))
		write.fmt(ehelp.obj,output,file=paste0(fnName,"-eHelp.html"))
	# HTML: output the help of the fn in HTML format + listing of the fn
	} else if (output == "HTML") {
		#write.html(ehelp.obj, ending="</P>", file=paste0(fnName,"-eHelp.HTML"))
		write.fmt(ehelp.obj,output,file=paste0(fnName,"-eHelp.HTML"),leaveOpen=T)
		write.Fncorpus(fnName, fnCorpus, file=paste0(fnName,"-eHelp.HTML"), begining="<p> <code>", ending="</code></p> \n </body> \n </HTML>", eol="<br> \n")
	# latex: output the help for the dn in LaTeX format
	} else if (output == "latex") {
		#write.latex(ehelp.obj, file=paste0(fnName,"-eHelp.tex"))
		write.fmt(ehelp.obj,output,paste0(fnName,"-eHelp.tex"))
	} else if (output == "LATEX") {
		#write.latex(ehelp.obj, ending="", file=paste0(fnName,"-eHelp.TEX"))
		write.fmt(ehelp.obj,output,paste0(fnName,"-eHelp.TEX"),leaveOpen=T)
		write.Fncorpus(fnName, fnCorpus, file=paste0(fnName,"-eHelp.TEX"),
			begining="\\section*{Listing}\n\\label{listing} \n \\begin{minipage}{0.75\\textwidth}\n \\small \n \\begin{verbatim}",
			ending="\\end{verbatim} \n \\end{minipage} \n\n \\end{document}",
			eol="\n")
	# ascii: same as plain-txt but with ESC-codes for coloring...
	} else if (output == "ascii") {
		#write.ascii(ehelp.obj, ending="", file=paste0(fnName,"-eHelp.asc"))
		write.fmt(ehelp.obj,output,file=paste0(fnName,"-eHelp.asc"))
	} else if (output == "ASCII") {
		#write.ascii(ehelp.obj, ending="", file=paste0(fnName,"-eHelp.ASC"))
		write.fmt(ehelp.obj,output,file=paste0(fnName,"-eHelp.ASC"), leaveOpen=T)
		write.Fncorpus(fnName, fnCorpus, file=paste0(fnName,"-eHelp.ASC"))
	} else if (output == "markdown") {
		write.fmt(ehelp.obj,output,paste0(fnName,"-eHelp.md"))
	} else if (output == "MARKDOWN") {
		write.fmt(ehelp.obj,output,paste0(fnName,"-eHelp.MD"), leaveOpen=T)
		write.Fncorpus(fnName, fnCorpus, file=paste0(fnName,"-eHelp.MD"),
			begining="```", ending="```", eol="\n")
	} else if (output != "none") {
		message("The selected output format <<",output,">> is not supported. \n",
			"Valid options are: ",paste0(valid.outputFmts,sep=" "),"\n")
		}
}


#####################


write.ehelp <- function(X.obj,filename){
#' function for writing ehelp output to a local text file
#' @param  X.obj  ehelp object
#' @param  filename  name of the file where to write the documentation
#' @keywords internal
        lines <- paste0("-----------------------",'\n')
        #X.obj <- c(lines,X.obj,lines)
        utils::write.table(X.obj,file=filename,sep="", col.names=FALSE,row.names=FALSE, quote=FALSE, eol="")
	write.Info(filename)

	message(paste(filename,"written to",getwd()))
}


######################

write.Fncorpus <- function(fnName, fnListing, lines=paste0("/* ################################################ */"), begining="", ending="", filename, eol="\n"){
#' Function to write into a file the listing of the fn.
#' @param  fnName   name of the function
#' @param  fnListing  listing of fn to write to file
#' @param  filename  name of the file where to write the documentation
#' @param  lines  optional argument to specify the separation lines to be used
#' @param  begining  an optional argument to specify the initial lines of HTML code
#' @param  ending  an optional argument to specify the last lines of HTML code
#' @param  eol   optional argument to specify the EOL (if need, eg. for html)
#' @keywords internal
        #lines <- paste0("/* ################################################ */")
	header <- c(lines,paste0("/* *** FUNCTION LISTING: ",fnName," ****/"),lines)
	# adding the "fn <-" which is supressed otherwise when capturing the fn
	fnListing[1] <- paste0(fnName, " <- ",fnListing[1])
        listing <- c(begining,header,fnListing,lines,ending)
        utils::write.table(listing,file=filename,sep="", col.names=FALSE,row.names=FALSE, quote=FALSE, append=TRUE, eol=eol)
}


write.Info <- function(filename, lines=paste0("-----------------------------------------------"), pre="", post="", eol="") {
#' function for including informaton about time and date in the generated files
#' @param  filename  name of the file where to write the documentation
#' @param  lines  optional argument to specify the separation lines to be used
#' @param  post  optional argument to specify post-information code to be added (if need, eg. for html)
#' @param  eol   optional argument to specify the EOL (if need, eg. for html)
#' @keywords internal
	# get some data from the current session
	date <- format(Sys.time(), "%a %b %d %X %Y")
	username <- Sys.info()["user"]
	sysinfo  <- Sys.info()["sysname"]
	sessionInfo <- sessionInfo()["R.version"]
	#lines <- paste0("-----------------------------------------------")
	output <- c(pre)
	output <- c(output,'\n',lines,'\n')
	output <- c(output,paste0("	Generated using the eHelp package -- ",date))
	output <- c(output,paste0('\n',"  User: ",username,"  --  System: ",sysinfo))
	output <- c(output,paste0("  ",sessionInfo$R.version$version.string,'\n'))
	output <- c(output,post)
	utils::write.table(output, file=filename,sep="", col.names=FALSE,row.names=FALSE, quote=FALSE, append=TRUE, eol=eol)
}


#################################################################################################

#################################################################################################


write.fmt <- function(X.obj, format, filename, leaveOpen=FALSE){
#' function for writing ehelp output to a local LaTeX file
#' @param  X.obj  ehelp object
#' @param  format  type of output: txt, latex, html
#' @param  filename  name of the file where to write the documentation
#' @param  leaveOpen  boolean argument to leave the file open
#' @keywords internal

	format <- tolower(format)
	
	# capture the text to output
        ehelp.txt <- X.obj$txt

	# load palettes
        formatting.codes <- ehelp.palette()

	# load format defns
	if (leaveOpen) {
		fmt <- format.defns(format,filename,ending="")
	} else {
		fmt <- format.defns(format,filename)
	}

	#print(fmt)

	# special consideration when the format is "ascii" => will keep ESC-codes for color
	if (format == "ascii") format <- "color"

        for (line in seq_along(ehelp.txt)) {
                lang.Code <- list("","")
                if (X.obj$code[line] %in% formatting.codes$codes)
                        lang.Code <- formatting.codes[[format]][ formatting.codes$codes == X.obj$code[line] ][[1]]
                ehelp.txt[line] <- paste0(lang.Code[[1]], ehelp.txt[line], lang.Code[[2]], fmt$eol) 

                # replace special characters depending on the format
		for (sp.char in fmt$sp.chars)
                	ehelp.txt[line] <- gsub(sp.char[[1]],sp.char[[2]],ehelp.txt[line])
        }

        # combine parts
        ehelp.txt <- c(fmt$struct, fmt$lines,ehelp.txt)	#,fmt$lines)
        #### 

        utils::write.table(ehelp.txt,file=filename,sep="", col.names=FALSE,row.names=FALSE, quote=FALSE, eol=fmt$eol)
        write.Info(filename, lines=fmt$lines, pre=fmt$pre, post=fmt$post, eol=fmt$eol)

        message(paste(filename,"written to",getwd(),'\n'))
}



#################################################################################################
#################################################################################################

